export enum MonsterType {
  DRAGON = "ドラゴン族",
  SPELLCASTER = "魔法使い族",
  ZONBIE = "アンデッド族",
  WARRIOR = "戦士族",
  BEAST_WARRIOR = "獣戦士族",
  BEAST = "獣族",
  WINGED_BEAST = "鳥獣族",
  FIEND = "悪魔族",
  FAIRY = "天使族",
  INSECT = "昆虫族",
  DINOSAUR = "恐竜族",
  REPTILE = "爬虫類族",
  FISH = "魚族",
  SEA_SERPENT = "海竜族",
  MACHINE = "機械族",
  THUNDER = "雷族",
  AQUA = "水族",
  PYRO = "炎族",
  ROCK = "岩石族",
  PLANT = "植物族",
  PSYCHIC = "サイキック族",
  WYRM = "幻竜族",
  CYBERSE = "サイバース族",
  DIVINE_BEAST = "幻神獣族",
  GOD = "創造神族"
}
